apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app-001
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valuesFiles:
        - values-prod.yaml
    path: helm
    repoURL: https://github.com/EmekaMomodu/basic-app-001
    targetRevision: HEAD
  syncPolicy: {}
